{"text": "2024-04-16 22:31:53 | INFO    | __main__:stash:131 | run - {'image': '20231121', 'version': '0.10.1.post2', 'role': 'EpicPlayer', 'headless': True}\n", "record": {"elapsed": {"repr": "0:00:01.455141", "seconds": 1.455141}, "exception": null, "extra": {"image": "20231121", "version": "0.10.1.post2", "role": "EpicPlayer", "headless": true}, "file": {"name": "claim.py", "path": "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/claim.py"}, "function": "stash", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 131, "message": "run", "module": "claim", "name": "__main__", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:31:53.797186+08:00", "timestamp": 1713277913.797186}}}
{"text": "2024-04-16 22:31:59 | WARNING    | epic_games.agent:get_order_history:467 | Failed to get order history, cookie may have expired - {}\n", "record": {"elapsed": {"repr": "0:00:07.274958", "seconds": 7.274958}, "exception": null, "extra": {}, "file": {"name": "agent.py", "path": "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/epic_games/agent.py"}, "function": "get_order_history", "level": {"icon": "‚ö†Ô∏è", "name": "WARNING", "no": 30}, "line": 467, "message": "Failed to get order history, cookie may have expired", "module": "agent", "name": "epic_games.agent", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:31:59.617003+08:00", "timestamp": 1713277919.617003}}}
{"text": "2024-04-16 22:32:00 | DEBUG    | __main__:create_tasks:66 | Put task - {'title': 'Ghostrunner', 'url': 'https://store.epicgames.com/en-US/p/ghostrunner'}\n", "record": {"elapsed": {"repr": "0:00:07.658271", "seconds": 7.658271}, "exception": null, "extra": {"title": "Ghostrunner", "url": "https://store.epicgames.com/en-US/p/ghostrunner"}, "file": {"name": "claim.py", "path": "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/claim.py"}, "function": "create_tasks", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 66, "message": "Put task", "module": "claim", "name": "__main__", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:32:00.000316+08:00", "timestamp": 1713277920.000316}}}
{"text": "2024-04-16 22:32:04 | INFO    | epic_games.agent:claim_weekly_games:294 | claim_weekly_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/p/ghostrunner'}\n", "record": {"elapsed": {"repr": "0:00:12.112884", "seconds": 12.112884}, "exception": null, "extra": {"action": "go to store", "url": "https://store.epicgames.com/en-US/p/ghostrunner"}, "file": {"name": "agent.py", "path": "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 294, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:32:04.454929+08:00", "timestamp": 1713277924.454929}}}
{"text": "2024-04-16 22:32:16 | INFO    | epic_games.agent:claim_weekly_games:326 | claim_weekly_games - {'action': 'move to webPurchaseContainer iframe'}\n", "record": {"elapsed": {"repr": "0:00:24.347115", "seconds": 24.347115}, "exception": null, "extra": {"action": "move to webPurchaseContainer iframe"}, "file": {"name": "agent.py", "path": "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 326, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:32:16.689160+08:00", "timestamp": 1713277936.68916}}}
{"text": "2024-04-16 22:32:19 | INFO    | epic_games.agent:claim_weekly_games:328 | claim_weekly_games - {'action': 'click payment button'}\n", "record": {"elapsed": {"repr": "0:00:26.798633", "seconds": 26.798633}, "exception": null, "extra": {"action": "click payment button"}, "file": {"name": "agent.py", "path": "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 328, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:32:19.140678+08:00", "timestamp": 1713277939.140678}}}
{"text": "2024-04-16 22:32:19 | ERROR    | hcaptcha_challenger.agents.playwright.control:handler:153 | 'utf-8' codec can't decode byte 0xf2 in position 7: invalid continuation byte - {}\nTraceback (most recent call last):\n  File \"/home/runner/work/Epic_Auto/Epic_Auto/epic/src/claim.py\", line 162, in <module>\n    asyncio.run(run())\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 636, in run_until_complete\n    self.run_forever()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n    self._run_once()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n    handle._run()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n> File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/hcaptcha_challenger/agents/playwright/control.py\", line 145, in handler\n    data = await response.json()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/async_api/_generated.py\", line 614, in json\n    return mapping.from_maybe_impl(await self._impl_obj.json())\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_network.py\", line 613, in json\n    return json.loads(await self.text())\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_network.py\", line 610, in text\n    return content.decode()\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xf2 in position 7: invalid continuation byte\n", "record": {"elapsed": {"repr": "0:00:27.473747", "seconds": 27.473747}, "exception": {"type": "UnicodeDecodeError", "value": "'utf-8' codec can't decode byte 0xf2 in position 7: invalid continuation byte", "traceback": true}, "extra": {}, "file": {"name": "control.py", "path": "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/hcaptcha_challenger/agents/playwright/control.py"}, "function": "handler", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 153, "message": "'utf-8' codec can't decode byte 0xf2 in position 7: invalid continuation byte", "module": "control", "name": "hcaptcha_challenger.agents.playwright.control", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:32:19.815792+08:00", "timestamp": 1713277939.815792}}}
{"text": "2024-04-16 22:32:53 | ERROR    | hcaptcha_challenger.agents.playwright.control:execute:615 | task interrupt <backcall> - {'reason': 'Failed to obtain challenge task'}\n", "record": {"elapsed": {"repr": "0:01:01.342925", "seconds": 61.342925}, "exception": null, "extra": {"reason": "Failed to obtain challenge task"}, "file": {"name": "control.py", "path": "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/hcaptcha_challenger/agents/playwright/control.py"}, "function": "execute", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 615, "message": "task interrupt <backcall>", "module": "control", "name": "hcaptcha_challenger.agents.playwright.control", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:32:53.684970+08:00", "timestamp": 1713277973.68497}}}
{"text": "2024-04-16 22:32:53 | DEBUG    | epic_games.agent:insert_challenge:106 | task done - {'sattus': 'success'}\n", "record": {"elapsed": {"repr": "0:01:01.343685", "seconds": 61.343685}, "exception": null, "extra": {"sattus": "success"}, "file": {"name": "agent.py", "path": "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/epic_games/agent.py"}, "function": "insert_challenge", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 106, "message": "task done", "module": "agent", "name": "epic_games.agent", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:32:53.685730+08:00", "timestamp": 1713277973.68573}}}
{"text": "2024-04-16 22:32:56 | ERROR    | hcaptcha_challenger.agents.playwright.control:handler:153 | 'utf-8' codec can't decode byte 0xb3 in position 0: invalid start byte - {}\nTraceback (most recent call last):\n  File \"/home/runner/work/Epic_Auto/Epic_Auto/epic/src/claim.py\", line 162, in <module>\n    asyncio.run(run())\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 636, in run_until_complete\n    self.run_forever()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n    self._run_once()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n    handle._run()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n> File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/hcaptcha_challenger/agents/playwright/control.py\", line 145, in handler\n    data = await response.json()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/async_api/_generated.py\", line 614, in json\n    return mapping.from_maybe_impl(await self._impl_obj.json())\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_network.py\", line 613, in json\n    return json.loads(await self.text())\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_network.py\", line 610, in text\n    return content.decode()\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xb3 in position 0: invalid start byte\n", "record": {"elapsed": {"repr": "0:01:03.680438", "seconds": 63.680438}, "exception": {"type": "UnicodeDecodeError", "value": "'utf-8' codec can't decode byte 0xb3 in position 0: invalid start byte", "traceback": true}, "extra": {}, "file": {"name": "control.py", "path": "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/hcaptcha_challenger/agents/playwright/control.py"}, "function": "handler", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 153, "message": "'utf-8' codec can't decode byte 0xb3 in position 0: invalid start byte", "module": "control", "name": "hcaptcha_challenger.agents.playwright.control", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:32:56.022483+08:00", "timestamp": 1713277976.022483}}}
{"text": "2024-04-16 22:33:25 | INFO    | epic_games.agent:claim_weekly_games:294 | claim_weekly_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/p/ghostrunner'}\n", "record": {"elapsed": {"repr": "0:01:33.590329", "seconds": 93.590329}, "exception": null, "extra": {"action": "go to store", "url": "https://store.epicgames.com/en-US/p/ghostrunner"}, "file": {"name": "agent.py", "path": "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 294, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:33:25.932374+08:00", "timestamp": 1713278005.932374}}}
{"text": "2024-04-16 22:33:35 | INFO    | epic_games.agent:claim_weekly_games:326 | claim_weekly_games - {'action': 'move to webPurchaseContainer iframe'}\n", "record": {"elapsed": {"repr": "0:01:42.919163", "seconds": 102.919163}, "exception": null, "extra": {"action": "move to webPurchaseContainer iframe"}, "file": {"name": "agent.py", "path": "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 326, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:33:35.261208+08:00", "timestamp": 1713278015.261208}}}
{"text": "2024-04-16 22:33:37 | INFO    | epic_games.agent:claim_weekly_games:328 | claim_weekly_games - {'action': 'click payment button'}\n", "record": {"elapsed": {"repr": "0:01:45.347465", "seconds": 105.347465}, "exception": null, "extra": {"action": "click payment button"}, "file": {"name": "agent.py", "path": "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 328, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:33:37.689510+08:00", "timestamp": 1713278017.68951}}}
{"text": "2024-04-16 22:33:38 | ERROR    | hcaptcha_challenger.agents.playwright.control:handler:153 | 'utf-8' codec can't decode byte 0xd0 in position 8: invalid continuation byte - {}\nTraceback (most recent call last):\n  File \"/home/runner/work/Epic_Auto/Epic_Auto/epic/src/claim.py\", line 162, in <module>\n    asyncio.run(run())\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 636, in run_until_complete\n    self.run_forever()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n    self._run_once()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n    handle._run()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n> File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/hcaptcha_challenger/agents/playwright/control.py\", line 145, in handler\n    data = await response.json()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/async_api/_generated.py\", line 614, in json\n    return mapping.from_maybe_impl(await self._impl_obj.json())\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_network.py\", line 613, in json\n    return json.loads(await self.text())\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_network.py\", line 610, in text\n    return content.decode()\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 8: invalid continuation byte\n", "record": {"elapsed": {"repr": "0:01:46.010642", "seconds": 106.010642}, "exception": {"type": "UnicodeDecodeError", "value": "'utf-8' codec can't decode byte 0xd0 in position 8: invalid continuation byte", "traceback": true}, "extra": {}, "file": {"name": "control.py", "path": "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/hcaptcha_challenger/agents/playwright/control.py"}, "function": "handler", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 153, "message": "'utf-8' codec can't decode byte 0xd0 in position 8: invalid continuation byte", "module": "control", "name": "hcaptcha_challenger.agents.playwright.control", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:33:38.352687+08:00", "timestamp": 1713278018.352687}}}
{"text": "2024-04-16 22:34:12 | ERROR    | hcaptcha_challenger.agents.playwright.control:execute:615 | task interrupt <backcall> - {'reason': 'Failed to obtain challenge task'}\n", "record": {"elapsed": {"repr": "0:02:19.892218", "seconds": 139.892218}, "exception": null, "extra": {"reason": "Failed to obtain challenge task"}, "file": {"name": "control.py", "path": "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/hcaptcha_challenger/agents/playwright/control.py"}, "function": "execute", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 615, "message": "task interrupt <backcall>", "module": "control", "name": "hcaptcha_challenger.agents.playwright.control", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:34:12.234263+08:00", "timestamp": 1713278052.234263}}}
{"text": "2024-04-16 22:34:12 | DEBUG    | epic_games.agent:insert_challenge:106 | task done - {'sattus': 'success'}\n", "record": {"elapsed": {"repr": "0:02:19.892977", "seconds": 139.892977}, "exception": null, "extra": {"sattus": "success"}, "file": {"name": "agent.py", "path": "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/epic_games/agent.py"}, "function": "insert_challenge", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 106, "message": "task done", "module": "agent", "name": "epic_games.agent", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:34:12.235022+08:00", "timestamp": 1713278052.235022}}}
{"text": "2024-04-16 22:34:14 | ERROR    | hcaptcha_challenger.agents.playwright.control:handler:153 | 'utf-8' codec can't decode byte 0x88 in position 0: invalid start byte - {}\nTraceback (most recent call last):\n  File \"/home/runner/work/Epic_Auto/Epic_Auto/epic/src/claim.py\", line 162, in <module>\n    asyncio.run(run())\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 636, in run_until_complete\n    self.run_forever()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n    self._run_once()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n    handle._run()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n> File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/hcaptcha_challenger/agents/playwright/control.py\", line 145, in handler\n    data = await response.json()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/async_api/_generated.py\", line 614, in json\n    return mapping.from_maybe_impl(await self._impl_obj.json())\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_network.py\", line 613, in json\n    return json.loads(await self.text())\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_network.py\", line 610, in text\n    return content.decode()\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 0: invalid start byte\n", "record": {"elapsed": {"repr": "0:02:22.302039", "seconds": 142.302039}, "exception": {"type": "UnicodeDecodeError", "value": "'utf-8' codec can't decode byte 0x88 in position 0: invalid start byte", "traceback": true}, "extra": {}, "file": {"name": "control.py", "path": "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/hcaptcha_challenger/agents/playwright/control.py"}, "function": "handler", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 153, "message": "'utf-8' codec can't decode byte 0x88 in position 0: invalid start byte", "module": "control", "name": "hcaptcha_challenger.agents.playwright.control", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:34:14.644084+08:00", "timestamp": 1713278054.644084}}}
{"text": "2024-04-16 22:34:44 | INFO    | epic_games.agent:claim_weekly_games:294 | claim_weekly_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/p/ghostrunner'}\n", "record": {"elapsed": {"repr": "0:02:52.162523", "seconds": 172.162523}, "exception": null, "extra": {"action": "go to store", "url": "https://store.epicgames.com/en-US/p/ghostrunner"}, "file": {"name": "agent.py", "path": "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 294, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:34:44.504568+08:00", "timestamp": 1713278084.504568}}}
{"text": "2024-04-16 22:34:53 | INFO    | epic_games.agent:claim_weekly_games:326 | claim_weekly_games - {'action': 'move to webPurchaseContainer iframe'}\n", "record": {"elapsed": {"repr": "0:03:01.584837", "seconds": 181.584837}, "exception": null, "extra": {"action": "move to webPurchaseContainer iframe"}, "file": {"name": "agent.py", "path": "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 326, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:34:53.926882+08:00", "timestamp": 1713278093.926882}}}
{"text": "2024-04-16 22:34:56 | INFO    | epic_games.agent:claim_weekly_games:328 | claim_weekly_games - {'action': 'click payment button'}\n", "record": {"elapsed": {"repr": "0:03:04.014502", "seconds": 184.014502}, "exception": null, "extra": {"action": "click payment button"}, "file": {"name": "agent.py", "path": "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 328, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:34:56.356547+08:00", "timestamp": 1713278096.356547}}}
{"text": "2024-04-16 22:34:56 | ERROR    | hcaptcha_challenger.agents.playwright.control:handler:153 | 'utf-8' codec can't decode byte 0xa6 in position 0: invalid start byte - {}\nTraceback (most recent call last):\n  File \"/home/runner/work/Epic_Auto/Epic_Auto/epic/src/claim.py\", line 162, in <module>\n    asyncio.run(run())\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 636, in run_until_complete\n    self.run_forever()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n    self._run_once()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n    handle._run()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n> File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/hcaptcha_challenger/agents/playwright/control.py\", line 145, in handler\n    data = await response.json()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/async_api/_generated.py\", line 614, in json\n    return mapping.from_maybe_impl(await self._impl_obj.json())\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_network.py\", line 613, in json\n    return json.loads(await self.text())\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_network.py\", line 610, in text\n    return content.decode()\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xa6 in position 0: invalid start byte\n", "record": {"elapsed": {"repr": "0:03:04.646636", "seconds": 184.646636}, "exception": {"type": "UnicodeDecodeError", "value": "'utf-8' codec can't decode byte 0xa6 in position 0: invalid start byte", "traceback": true}, "extra": {}, "file": {"name": "control.py", "path": "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/hcaptcha_challenger/agents/playwright/control.py"}, "function": "handler", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 153, "message": "'utf-8' codec can't decode byte 0xa6 in position 0: invalid start byte", "module": "control", "name": "hcaptcha_challenger.agents.playwright.control", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:34:56.988681+08:00", "timestamp": 1713278096.988681}}}
{"text": "2024-04-16 22:35:30 | ERROR    | hcaptcha_challenger.agents.playwright.control:execute:615 | task interrupt <backcall> - {'reason': 'Failed to obtain challenge task'}\n", "record": {"elapsed": {"repr": "0:03:38.560023", "seconds": 218.560023}, "exception": null, "extra": {"reason": "Failed to obtain challenge task"}, "file": {"name": "control.py", "path": "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/hcaptcha_challenger/agents/playwright/control.py"}, "function": "execute", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 615, "message": "task interrupt <backcall>", "module": "control", "name": "hcaptcha_challenger.agents.playwright.control", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:35:30.902068+08:00", "timestamp": 1713278130.902068}}}
{"text": "2024-04-16 22:35:30 | DEBUG    | epic_games.agent:insert_challenge:106 | task done - {'sattus': 'success'}\n", "record": {"elapsed": {"repr": "0:03:38.560849", "seconds": 218.560849}, "exception": null, "extra": {"sattus": "success"}, "file": {"name": "agent.py", "path": "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/epic_games/agent.py"}, "function": "insert_challenge", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 106, "message": "task done", "module": "agent", "name": "epic_games.agent", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:35:30.902894+08:00", "timestamp": 1713278130.902894}}}
{"text": "2024-04-16 22:35:33 | ERROR    | hcaptcha_challenger.agents.playwright.control:handler:153 | 'utf-8' codec can't decode byte 0xe6 in position 0: invalid continuation byte - {}\nTraceback (most recent call last):\n  File \"/home/runner/work/Epic_Auto/Epic_Auto/epic/src/claim.py\", line 162, in <module>\n    asyncio.run(run())\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 636, in run_until_complete\n    self.run_forever()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n    self._run_once()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n    handle._run()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n> File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/hcaptcha_challenger/agents/playwright/control.py\", line 145, in handler\n    data = await response.json()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/async_api/_generated.py\", line 614, in json\n    return mapping.from_maybe_impl(await self._impl_obj.json())\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_network.py\", line 613, in json\n    return json.loads(await self.text())\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_network.py\", line 610, in text\n    return content.decode()\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xe6 in position 0: invalid continuation byte\n", "record": {"elapsed": {"repr": "0:03:40.922245", "seconds": 220.922245}, "exception": {"type": "UnicodeDecodeError", "value": "'utf-8' codec can't decode byte 0xe6 in position 0: invalid continuation byte", "traceback": true}, "extra": {}, "file": {"name": "control.py", "path": "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/hcaptcha_challenger/agents/playwright/control.py"}, "function": "handler", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 153, "message": "'utf-8' codec can't decode byte 0xe6 in position 0: invalid continuation byte", "module": "control", "name": "hcaptcha_challenger.agents.playwright.control", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:35:33.264290+08:00", "timestamp": 1713278133.26429}}}
{"text": "2024-04-16 22:36:02 | ERROR    | __main__:run:158 | An error has been caught in function 'run', process 'MainProcess' (3955), thread 'MainThread' (140588097727360): - {}\nTraceback (most recent call last):\n  File \"/home/runner/work/Epic_Auto/Epic_Auto/epic/src/claim.py\", line 151, in stash\n    await self.claim_epic_games(context)\n  File \"/home/runner/work/Epic_Auto/Epic_Auto/epic/src/claim.py\", line 122, in claim_epic_games\n    await epic.claim_weekly_games(page, single_promotions)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/_asyncio.py\", line 88, in async_wrapped\n    return await fn(*args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/_asyncio.py\", line 47, in __call__\n    do = self.iter(retry_state=retry_state)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/__init__.py\", line 325, in iter\n    raise retry_exc.reraise()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/__init__.py\", line 158, in reraise\n    raise self.last_attempt.result()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/concurrent/futures/_base.py\", line 451, in result\n    return self.__get_result()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/_asyncio.py\", line 50, in __call__\n    result = await fn(*args, **kwargs)\n  File \"/home/runner/work/Epic_Auto/Epic_Auto/epic/src/epic_games/agent.py\", line 338, in claim_weekly_games\n    await page.wait_for_url(recur_url)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/async_api/_generated.py\", line 8776, in wait_for_url\n    await self._impl_obj.wait_for_url(\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_page.py\", line 524, in wait_for_url\n    return await self._main_frame.wait_for_url(**locals_to_params(locals()))\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py\", line 233, in wait_for_url\n    async with self.expect_navigation(\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_event_context_manager.py\", line 33, in __aexit__\n    await self._future\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py\", line 208, in continuation\n    event = await waiter.result()\nplaywright._impl._errors.TimeoutError: Timeout 30000ms exceeded.\n=========================== logs ===========================\nwaiting for navigation to \"https://store.epicgames.com/en-US/cart/success\" until 'load'\n============================================================\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/work/Epic_Auto/Epic_Auto/epic/src/claim.py\", line 162, in <module>\n    asyncio.run(run())\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 636, in run_until_complete\n    self.run_forever()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n    self._run_once()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n    handle._run()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n> File \"/home/runner/work/Epic_Auto/Epic_Auto/epic/src/claim.py\", line 158, in run\n    await agent.stash()\n  File \"/home/runner/work/Epic_Auto/Epic_Auto/epic/src/claim.py\", line 139, in stash\n    async with async_playwright() as p:\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/async_api/_context_manager.py\", line 57, in __aexit__\n    await self._connection.stop_async()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py\", line 285, in stop_async\n    self.cleanup()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py\", line 296, in cleanup\n    callback.future.set_exception(self._closed_error)\nasyncio.exceptions.InvalidStateError: invalid state\n", "record": {"elapsed": {"repr": "0:04:10.457013", "seconds": 250.457013}, "exception": {"type": "InvalidStateError", "value": "invalid state", "traceback": true}, "extra": {}, "file": {"name": "claim.py", "path": "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/claim.py"}, "function": "run", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 158, "message": "An error has been caught in function 'run', process 'MainProcess' (3955), thread 'MainThread' (140588097727360):", "module": "claim", "name": "__main__", "process": {"id": 3955, "name": "MainProcess"}, "thread": {"id": 140588097727360, "name": "MainThread"}, "time": {"repr": "2024-04-16 22:36:02.799058+08:00", "timestamp": 1713278162.799058}}}
